language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t paulrody/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true paulrody/docker-react npm run test